### ISSUE TITLE
Personal Data element in template

### ISSUE THREAD

**Issue by markwilkinson** [ejp-rd-vp/resource-metadata-schema#43]
The valid values for xsd:boolean are "true", "false", "1", "0"

yes/no are not valid values...

**Comment by markwilkinson** [comment]
By the way... the FAIR Data Point cannot create booleans... so we cannot enforce this...

**Comment by markwilkinson** [comment]
Decision:  personal data element is optional; has a strong value of "true" or "false" because we cannot capture it in the FDP anyway.  Decision being ratified at the P2 meeting this friday

**Comment by markwilkinson** [comment]
PLEASE HOLD ON THIS CHANGE - there are still discussions happening, so this isn't decided yet

**Comment by henrietteharmse** [comment]
Wrt yes/no versus true/false or 1/0, I think we should distinguish between a template that is suppose to be human readable (my assumption!)  vs machine readable. My reason for using yes/no rather than true/false or 1/0 is that I assumed people will fill in the template. However, this does not mean when imported it should be imported as yes/no. Rather, during import there should be a translation from yes->true/1 and no->no/0. 

 I just wanted to make clear the reason for using yes/no. But I am happy to change whichever way we decide.

**Comment by markwilkinson** [comment]
Final decision:  personalData is optional, associated with Resource, and has the string value "true" or "false" (all lower case).  (Making it mandatory will be at the level of onboarding policy decisions, not enforced at the level of the schema.)

**Comment by henrietteharmse** [comment]
Can be removed from all except Resource

**Comment by henrietteharmse** [comment]
personalData should be xsd:string for now.
