### ISSUE TITLE
Biobank and PatientRegistry as disjoint sub-types of Resource

### ISSUE THREAD

**Issue by luizbonino** [ejp-rd-vp/resource-metadata-schema#58]
During the L1/L2 meeting an issue was raised concerning resources that present themselves as both Biobank and PatientRegistry. In the group's discussion, we concluded that a given resource should only be declared as one of these types, not both. Although in the metadata schema they have the same set of properties, these entities are of different nature. Naturally, a biobank (or multiple) and a patient registry (or multiple) can be managed by or belong to a single organisation. However, we consider that the focus of EJP-RD is on the informational resources and not on the organisations managing them.

The request is to make clear that these sub-classes are disjoint in the diagram, related ontology and documentation.

**Comment by henrietteharmse** [comment]
@luizbonino Should the disjointness statement include Guideline, Dataset and DataService since they as well extend Resources? In general classes in a UML class diagram are considered to be disjoint. This was also the case for generalizations, but that seemed to have changed from UML 2.5.0, which I did not realize.

**Comment by luizbonino** [comment]
> 

Thanks Henriette. Yes, until UML 2.4.1, generalisation sets were incomplete and disjoint by default. In UML 2.5 they changed the defaults to incomplete and overlapping.
