### ISSUE TITLE
`dcat:contactPoint` is obligatory but not in the shape expression

### ISSUE THREAD

**Issue by egonw** [ejp-rd-vp/resource-metadata-schema#77]
The field `dcat:contactPoint` is obligatory according to [this page]()https://vp-onboarding-doc.readthedocs.io/en/latest/level_1/properties/data_service.html but not in the `dataservices.shex` shape expression [here](https://github.com/ejp-rd-vp/resource-metadata-schema/blob/master/shapes/dataservices.shex).

**Comment by markwilkinson** [comment]
I have (I hope??) fixed the ShEx that you are referring to.  I was honestly unaware that these shapes existed!  AFAIK they are not being maintained (at least, not by me... they were under the supervision of Henriette.  My name appears in the commit logs only because I made a global change to hundreds of files when we changed the EJP namespace from purl to w3id...)

I will ask around, and if nobody is going to take responsibility to curate them, I will flag them as deprecated.  It would be better for us to focus on just one shape representation (I prefer SHACL) and maintain it consistently throughout the project.
